<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>N&O Drive</title>
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
  }
  .header {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 20px 0;
  }
  .button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 8px;
  }
</style>
</head>
<body>
<div class="header">
  <h1>N&O Drive</h1>
</div>
<div style="text-align: center; margin-top: 50px;">
  <button class="button" onclick="document.getElementById('fileInput').click();">לבחירת הקובץ</button>
  <input type="file" id="fileInput" style="display:none;">
</div>
</body>
</html>
